apiVersion: apps/v1
kind: Deployment
metadata:
  name: primuslearning
  labels:
    app: primuslearning
spec:
  replicas: 1
  selector:
    matchLabels:
      app: primuslearning
  template:
    metadata:
      labels:
        app: primuslearning
    spec:
      containers:
        - name: primuslearning
          image: 243560554745.dkr.ecr.eu-west-3.amazonaws.com/fesia255:1.1
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
